
name: Go Microservice CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
        
    - name: Initialize Go module
      run: go mod init main

    - name: Build and test
      run: |
        go build
        go test ./...

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        # Add your deployment script or commands here
        # For example, you can use tools like Docker to containerize your app and deploy it to a server.
        # This example assumes a simple deployment where you run the compiled binary.

        ./main &

        # Sleep for a few seconds to let the server start
        sleep 5

        # Test the API endpoint
        curl http://localhost:8080/api/hello
