
name: Go Microservice CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
        
    - name: Initialize Go module
      run: go mod init main

    - name: Build and test
      run: |
        go build
        go test ./...

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        ./main > server.log 2>&1 &
        sleep 30s
        cat server.log
        curl http://localhost:8080/api/hello
        curl http://localhost:8080/api/whoami
