name: learn-accuknox-report-action
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  check-working:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            submodules: true
            
        - name: Checkout kubearmor repo
          uses: actions/checkout@v3
          with:
            repository: kubearmor/KubeArmor
            ref: main
            path: Kubearmor
  
        - name: Setup a Kubernetes environment
          run: |
            ./Kubearmor/contribution/k3s/install_k3s.sh
             sudo apt install socat
        
        - name: Install accuknoxcli, KubeArmor and Discovery Engine
          uses: accuknox/install-action@v0.1.1 

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.16'
        
        - name: Initialize Go module
          run: go mod init main

        - name: Build and test
          run: |
            go build
            go test ./...

        - name: Dockerize
          run: |
            docker build -t my-golang-app .
            mkdir -p $HOME/docker-images
            docker save -o $HOME/docker-images/my-golang-app.tar my-golang-app

        - name: Load Docker image locally
          run: docker load -i $HOME/docker-images/my-golang-app.tar

        - name: Deploy to Kubernetes
          run: |
            kubectl apply -f k8s/deployment.yaml
            sleep 120s
            POD_NAME=$(kubectl get pods -l app=my-golang-app -o jsonpath="{.items[0].metadata.name}")
            echo "POD_NAME=${POD_NAME}" >> $GITHUB_ENV

        - name: Check Pod Status
          run: kubectl get pods

        - name: Check Pod Events
          run: kubectl describe pod $POD_NAME
        
        - name: Test API endpoints
          run: |
            kubectl port-forward svc/my-golang-app 8080:8080 &
            sleep 30s
            curl http://localhost:8080/api/hello
 
        - name: Generate Report
          uses: accuknox/report-action@v0.1.2

