name: learn-accuknox-report-action
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
jobs:
  check-working:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
          with:
            submodules: true
            
        - name: Checkout kubearmor repo
          uses: actions/checkout@v3
          with:
            repository: kubearmor/KubeArmor
            ref: main
            path: Kubearmor
  
        - name: Setup a Kubernetes environment
          run: |
            ./Kubearmor/contribution/k3s/install_k3s.sh
             sudo apt install socat
        
        - name: Install accuknoxcli, KubeArmor and Discovery Engine
          uses: accuknox/install-action@v0.1.1 

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.16'
        
        - name: Initialize Go module
          run: go mod init main

        - name: Build and test
          run: |
            go build
            go test ./...
        
        - name: Dockerize and Push to Docker Hub
          run: |
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              docker build -t "${{ secrets.DOCKER_USERNAME }}/helloapp:latest" .
              docker push "${{ secrets.DOCKER_USERNAME }}/helloapp:latest"

        - name: Apply kubearmor policy to block package management tool executions
          run: |
            kubectl apply -f k8s/pkgpolicyblock.yaml
            sleep 30s
            kubectl get ksp

        - name: Deploy to Kubernetes
          run: |
            kubectl apply -f k8s/deployment.yaml
            sleep 120s
            POD_NAME=$(kubectl get pods -l app=my-golang-app -o jsonpath="{.items[0].metadata.name}")
            echo "POD_NAME=${POD_NAME}" >> $GITHUB_ENV

        - name: Check Pod Status
          run: kubectl get pods

        - name: Check Pod Events
          run: kubectl describe pod $POD_NAME

        - name: Display pod files
          run: kubectl exec -it $POD_NAME -- apt-get update
        
        - name: Test API endpoints
          run: |
            kubectl port-forward svc/my-golang-app 8080:8080 &
            sleep 31s
            curl http://localhost:8080/api/newyork
            curl http://localhost:8080/api/hello
            curl http://localhost:8080/api/hello
            #curl http://localhost:8080/api/hello
            curl http://localhost:8080/api/whoami
            curl http://localhost:8080/api/whoami
            cat /etc/passwd
            sleep 60s
            curl http://localhost:8080/api/hello
            curl http://localhost:8080/api/hello
            curl http://localhost:8080/api/whoami
            curl http://localhost:8080/api/whoami
            cat /etc/passwd
            #sleep 240s
            
        - name: Generate Report
          uses: accuknox/report-action@v0.1.2
          with: 
            baseline-report-path: "baseline/report.json"
            namespaces: "default"
